name: Create and publish release for github

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: default
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Get version
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      id: get_version

    - name: Build with Maven
      run: mvn package
      id: build_maven


    - name: Zip source code
      run: zip -r source-code.zip .
      working-directory: ${{ github.workspace }}
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./target/wso2-mi-xfcc-mediator-${{ env.RELEASE_VERSION }}.jar
          source-code.zip
        tag_name: v${{ env.RELEASE_VERSION }}
        name: Release v${{ env.RELEASE_VERSION }}
        body: |
          Release v${{ env.RELEASE_VERSION }} for the wso2-mi-xfcc-mediator.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
